name: Node.js CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

      run: yarn install

    - name: build
      run: yarn build

    - name: test
      run: yarn test
