name: Node.js CI

on: [push]

permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: install
      run: yarn install --frozen-lockfile

    - name: build
      run: yarn build

    - name: test
      run: yarn test
      env:
        CI: true
